image:
  - "Visual Studio 2017"

shallow_clone: true

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  MSYS_DIR: C:\msys64\usr\bin
  Path: C:\Python34-x64;%MINGW_DIR%;%Path%
  matrix:
    -
      BUILD_TYPE: release
      CMAKE_BUILD: cygwin
      STATIC_LIBS: false
      UNIT_TESTS: true
      CYGWIN_NOWINPATH: yes
      clone_folder: "C:\\cygwin\\projects\\NJOY21"
      CYG_BASH: C:\cygwin\bin\bash
      CYG_CACHE: C:\cygwin\var\cache\setup
      CYG_MIRROR: http://cygwin.mirror.constant.com
      CYG_ROOT: C:\cygwin
      CC: /bin/clang
      CXX: /bin/clang++
      FC: /bin/gfortran
#    -
#      BUILD_TYPE: release
#      CMAKE_BUILD: cygwin
#      STATIC_LIBS: true
#      UNIT_TESTS: true
#      CYGWIN_NOWINPATH: yes
#      clone_folder: "C:\\cygwin\\projects\\NJOY21"
#      CYG_BASH: C:\cygwin\bin\bash
#      CYG_CACHE: C:\cygwin\var\cache\setup
#      CYG_MIRROR: http://cygwin.mirror.constant.com
#      CYG_ROOT: C:\cygwin
#      CC: /usr/bin/clang
#      CXX: /usr/bin/clang++
#      FC: /usr/bin/gfortran
#    -
#      BUILD_TYPE: release
#      CMAKE_BUILD: cygwin
#      STATIC_LIBS: false
#      UNIT_TESTS: true
#      CYGWIN_NOWINPATH: yes
#      clone_folder: "C:\\cygwin\\projects\\NJOY21"
#      CYG_BASH: C:\cygwin\bin\bash
#      CYG_CACHE: C:\cygwin\var\cache\setup
#      CYG_MIRROR: http://cygwin.mirror.constant.com
#      CYG_ROOT: C:\cygwin
#      CC: /usr/bin/gcc
#      CXX: /usr/bin/g++
#      FC: /usr/bin/gfortran
#    -
#      BUILD_TYPE: release
#      CMAKE_BUILD: cygwin
#      STATIC_LIBS: true
#      UNIT_TESTS: true
#      CYGWIN_NOWINPATH: yes
#      clone_folder: "C:\\cygwin\\projects\\NJOY21"
#      CYG_BASH: C:\cygwin\bin\bash
#      CYG_CACHE: C:\cygwin\var\cache\setup
#      CYG_MIRROR: http://cygwin.mirror.constant.com
#      CYG_ROOT: C:\cygwin
#      CC: /usr/bin/gcc
#      CXX: /usr/bin/g++
#      FC: /usr/bin/gfortran
    -
      BUILD_TYPE: release
      CMAKE_BUILD: MSYS
      STATIC_LIBS: true
      UNIT_TESTS: false
      clone_folder: "C:\\projects\\NJOY21"
      CC: "%MSYS_DIR%\\gcc.exe"
      CXX: "%MSYS_DIR%\\g++.exe"
      FC: "%MSYS_DIR%\\gfortran.exe"
      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MSYS_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\Program Files\\Git\\usr\\bin"
#    -
#      BUILD_TYPE: release
#      CMAKE_BUILD: MSYS
#      STATIC_LIBS: false
#      UNIT_TESTS: false
#      clone_folder: "C:\\projects\\NJOY21"
#      CC: "%MSYS_DIR%\\gcc.exe"
#      CXX: "%MSYS_DIR%\\g++.exe"
#      FC: "%MSYS_DIR%\\gfortran.exe"
#      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MSYS_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\Program Files\\Git\\usr\\bin"
#    -
#      BUILD_TYPE: release
#      CMAKE_BUILD: MSYS
#      STATIC_LIBS: true
#      UNIT_TESTS: true
#      clone_folder: "C:\\projects\\NJOY21"
#      CC: "%MSYS_DIR%\\gcc.exe"
#      CXX: "%MSYS_DIR%\\g++.exe"
#      FC: "%MSYS_DIR%\\gfortran.exe"
#      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MSYS_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\Program Files\\Git\\usr\\bin"
#    -
#      BUILD_TYPE: release
#      CMAKE_BUILD: MSYS
#      STATIC_LIBS: false
#      UNIT_TESTS: true
#      clone_folder: "C:\\projects\\NJOY21"
#      CC: "%MSYS_DIR%\\gcc.exe"
#      CXX: "%MSYS_DIR%\\g++.exe"
#      FC: "%MSYS_DIR%\\gfortran.exe"
#      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MSYS_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\Program Files\\Git\\usr\\bin"
    -
      BUILD_TYPE: release
      CMAKE_BUILD: MinGW
      STATIC_LIBS: true
      UNIT_TESTS: false
      clone_folder: "C:\\projects\\NJOY21"
      CC: "%MINGW_DIR%\\gcc.exe"
      CXX: "%MINGW_DIR%\\g++.exe"
      FC: "%MINGW_DIR%\\gfortran.exe"
      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\Program Files\\Git\\usr\\bin"
#    -
#      BUILD_TYPE: release
#      CMAKE_BUILD: MinGW
#      STATIC_LIBS: false
#      UNIT_TESTS: false
#      clone_folder: "C:\\projects\\NJOY21"
#      CC: "%MINGW_DIR%\\gcc.exe"
#      CXX: "%MINGW_DIR%\\g++.exe"
#      FC: "%MINGW_DIR%\\gfortran.exe"
#      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\Program Files\\Git\\usr\\bin"
#    -
#      BUILD_TYPE: release
#      CMAKE_BUILD: MinGW
#      STATIC_LIBS: true
#      UNIT_TESTS: true
#      clone_folder: "C:\\projects\\NJOY21"
#      CC: "%MINGW_DIR%\\gcc.exe"
#      CXX: "%MINGW_DIR%\\g++.exe"
#      FC: "%MINGW_DIR%\\gfortran.exe"
#      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\Program Files\\Git\\usr\\bin"
#    -
#      BUILD_TYPE: release
#      CMAKE_BUILD: MinGW
#      STATIC_LIBS: false
#      UNIT_TESTS: true
#      clone_folder: "C:\\projects\\NJOY21"
#      CC: "%MINGW_DIR%\\gcc.exe"
#      CXX: "%MINGW_DIR%\\g++.exe"
#      FC: "%MINGW_DIR%\\gfortran.exe"
#      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\Program Files\\Git\\usr\\bin"
    -
      BUILD_TYPE: release
      CMAKE_BUILD: MinGW
      STATIC_LIBS: true
      UNIT_TESTS: false
      clone_folder: "C:\\projects\\NJOY21"
      CC: "C:\\Program Files\\LLVM\\bin\\clang.exe"
      CXX: "C:\\Program Files\\LLVM\\bin\\clang++.exe"
      FC: "%MINGW_DIR%\\gfortran.exe"
      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64\\usr\\bin;C:\\Program Files\\Git\\usr\\bin"

install:
  - if [%CMAKE_BUILD%]==[cygwin] C:\cygwin\setup-x86.exe -q --root %CYG_ROOT% --local-package-dir %CYG_CACHE% --packages cmake,make,git,python3,gcc,gcc-g++,gcc-fortran,clang --force-current --no-shortcuts --no-startmenu --no-desktop
  - if [%CMAKE_BUILD%]==[cygwin] %CYG_BASH% -c "export PATH=$PATH:/usr/bin && which -a clang++"
  - if [%CMAKE_BUILD%]==[cygwin] %CYG_BASH% -c "export PATH=$PATH:/usr/bin && which -a g++"
  - if [%CMAKE_BUILD%]==[cygwin] %CYG_BASH% -c "export PATH=$PATH:/usr/bin && which -a gfortran"
  - if [%CMAKE_BUILD%]==[cygwin] %CYG_BASH% -c "export PATH=$PATH:/usr/bin && ls -la /usr/bin/"
  - if not [%CMAKE_BUILD%]==[cygwin] dir C:\msys64\usr\bin\
  - if not [%CMAKE_BUILD%]==[cygwin] dir C:\msys64\mingw64\bin\

before_build:
  - if not [%CMAKE_BUILD%]==[cygwin] set OrigPath=%Path%
  - if [%CMAKE_BUILD%]==[cygwin] set Path=C:\cygwin\bin

build_script:
  - mkdir build
  - cd build
  - if [%CMAKE_BUILD%]==[cygwin] %CYG_BASH% -c "export PATH=$PATH:/usr/bin && /usr/bin/cmake -D build_type=%BUILD_TYPE% -D static=%STATIC_LIBS% -D unit_tests=%UNIT_TESTS% -G \"Unix Makefiles\" .."
  - if [%CMAKE_BUILD%]==[cygwin] %CYG_BASH% -c "export PATH=$PATH:/usr/bin && /usr/bin/make -j2"
# Non-cygwin builds
  - if not [%CMAKE_BUILD%]==[cygwin] set Path=%TMP_PATH%
  - if not [%CMAKE_BUILD%]==[cygwin] cmake -D CMAKE_Fortran_COMPILER=C:/msys64/usr/bin/gfortran.exe -D CMAKE_MAKE_PROGRAM=C:/msys64/usr/bin/mingw32-make.exe -D static=%STATIC_LIBS% -D unit_tests=%UNIT_TESTS% -G "%CMAKE_BUILD% Makefiles" ..
  - if not [%CMAKE_BUILD%]==[cygwin] set Path=%OrigPath%
  - if not [%CMAKE_BUILD%]==[cygwin] mingw32-make -j2

after_build:
  - if [%CMAKE_BUILD%]==[cygwin] %CYG_BASH% -c "export PATH=$PATH:/usr/bin && /usr/bin/ctest -j2 --output-on-failure"
  - if not [%CMAKE_BUILD%]==[cygwin] ctest -j2 --output-on-failure
